name: Deploy Laravel Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Adjust PHP version according to your needs

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-dev --no-progress --no-suggest

    - name: Upload files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ftp://${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /home/your-username/public_html # Replace with your actual home directory
